components:
  parameters:
    pageParam:  
      in: query
      name: page
      required: false
      schema:
        type: integer
        minimum: 1
        default: 1
      description: The number of items to skip before starting to collect the result set.
    limitParam:
      in: query
      name: limit
      required: false
      schema:
        type: integer
        minimum: 1
        maximum: 5000
        default: 10
      description: The numbers of items to return.
    filterParams:
      in: query
      name: filters
      content: 
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
            example: { "_id": "5fe1cd34b8c599163c04d7e5" }
    sortParams:  
      in: query
      name: sort
      schema: 
          type: string
          default: createdAt
    orderParams:  
      in: query
      name: order
      schema: 
        type: string
        default: acs
        enum:
          - acs
          - desc